name: Validate JSONs

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate IBC JSON
        uses: GrantBirki/json-yaml-validate@v2.3.0
        with:
          comment: "true"
          json_schema: frontend/config/jsons/schemas/ibcChannels.schema.json
          files: frontend/config/jsons/ibcChannels.json
      - name: Validate Layer Zero JSON
        uses: GrantBirki/json-yaml-validate@v2.3.0
        with:
          comment: "true"
          json_schema: frontend/config/jsons/schemas/layerZeroChainIds.schema.json
          files: frontend/config/jsons/layerZeroChainIds.json
      - name: Validate Bridge Out Tokens
        uses: GrantBirki/json-yaml-validate@v2.3.0
        with:
          comment: "true"
          json_schema: frontend/config/jsons/schemas/bridgeOutTokens.schema.json
          files: frontend/config/jsons/bridgeOutTokens.json
      - name: Validate Bridge In Tokens
        uses: GrantBirki/json-yaml-validate@v2.3.0
        with:
          comment: "true"
          json_schema: frontend/config/jsons/schemas/bridgeInTokens.schema.json
          files: frontend/config/jsons/bridgeInTokens.json
