name: Validate JSONs

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON
        uses: GrantBirki/json-yaml-validate@v2.3.0
        env:
          json_schema: config/jsons/schemas/ibcChannels.schema.json
          files: config/jsons/ibcChannels.json
